[tool.poetry]
name = "atcoder"
version = "0.1.0"
description = ""
authors = ["Hinata Yoshida <h-yoshida@toki.waseda.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.8.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
